import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DynamicHeader from "@/components/DynamicHeader";
import Footer from "@/components/Footer";
import { StoreProvider } from "@/stores/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Civic Form",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body>
          <StoreProvider>
            <main
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <DynamicHeader />
              {children}
            </main>
          </StoreProvider>
        </body>
      </html>
      <Footer />
    </>
  );
}
